repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.80.0
  hooks:
   - id: terraform_tflint
     args:
     - --args=--format=compact
   - id: terraform_checkov
     args:
       - --args=--quiet
       - --args=--skip-check HIGH
       - --args=--download-external-modules true
